### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by anonfantom** [encounter/futurerestore#12] opened 2018-01-19 22:10 UTC
mohammads-mbp:futurerestore_macos_v173 mohammad$ ./futurerestore 
Illegal instruction: 4 
MacOS Version 10.13.2 (17C205)
otool -L futurerestore output : 
futurerestore:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1450.15.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
I'm trying to update my 6s from 10.2 to 11.1.2 
Thanks

**Comment by encounter** [comment] 2018-01-19 22:24
Duplicate of #11, I'm investigating.

**Closed by encounter** 2018-01-19 22:24 UTC

**Comment by goodboydheeraj** [comment] 2018-02-02 19:13
Try this debug version & report back https://github.com/encounter/futurerestore/files/1650191/futurerestore_macos_DEBUG3.zip

**Comment by DaveFlash** [comment] 2018-03-21 08:46
that version doesnt work for me, gives this error now: 

Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173

Odysseus Support: no

[Error] argument parsing failed! agrc=6 optind=3
